#!/usr/bin/python
import sys
import shutil
import os

CURRENT_DIR = os.getcwd()
BACKUP_DIR = os.path.join(CURRENT_DIR, ".levcs")

def checkout_latest():
    latest = get_latest_version()
    checkout(latest)

def checkout(version):
    version_dir = os.path.join(BACKUP_DIR, str(version))
    if not os.path.isdir(version_dir):
        print "Version", version, "not found."
    else:
        # Delete everything in working dir EXCEPT .levcs/
        to_remove = [f for f in os.listdir(CURRENT_DIR) if f != ".levcs"]
        print "Removing:", to_remove
        for f in to_remove:
            try:
                os.remove(f)
            except OSError:
                shutil.rmtree(f)

        # Copy everything in .levcs/version/ to working dir
        print os.walk(version_dir).next()
        root, dirs, files = os.walk(version_dir).next()
        for d in dirs:
            shutil.copytree(os.path.join(root, d), os.path.join(CURRENT_DIR, d))
        for f in files:
            shutil.copy(os.path.join(root, f), os.path.join(CURRENT_DIR, f))

        print "Checked out version", version

def make_backup():
    print BACKUP_DIR

    if not os.path.isdir(BACKUP_DIR):
        version = 1
    else:
        version = get_next_version()

    next_version_dir = os.path.join(BACKUP_DIR, str(version))

    shutil.copytree(CURRENT_DIR, next_version_dir, ignore=shutil.ignore_patterns('.levcs*'))
    print "Backed up to", next_version_dir

def get_next_version():
    return get_latest_version() + 1

def get_latest_version():
    return len(os.listdir(BACKUP_DIR))


def print_help():
    print "RTFM"


if __name__ == "__main__":

    if len(sys.argv) == 1:
        print_help()

    elif sys.argv[1] == "backup":
        make_backup()

    elif sys.argv[1] == "checkout":
        try:
            version = sys.argv[2]
        except:
            print "Please provide a version number, for example:"
            print "levcs.py checkout 1"
        else:
            checkout(version)
    elif sys.argv[1] == "latest":
        checkout_latest()
